In [1]:
import pandas as pd
import random
import numpy as np

In [2]:
def process_packet_data(df):
    # Function to process each row's 'Data' column
    def process_packets(packets):
        # Keep only the first 32 packets
        truncated_packets = packets[:32]
        
        # Remove the timestamp from each packet
        processed_packets = [[packet[1], packet[2], packet[3]] for packet in truncated_packets]
        
        return processed_packets

    # Apply the function to each row's 'Data' column
    df['Data'] = df['Data'].apply(process_packets)
    
    return df

In [3]:
def process_packet_data_to_numpy(df):
    # Function to process each row's 'Data' column
    def process_packets_to_numpy(packets):
        truncated_packets = packets[:32]
        #print(truncated_packets)
        processed_packets = [[float(packet[1]), int(packet[2]), int(packet[3])] for packet in truncated_packets]
        return np.array(processed_packets)
    
    # Apply the function to each row's 'Data' column
    df['Data'] = df['Data'].apply(process_packets_to_numpy)
    
    return df

In [2]:
# Create DataFrame
#df = pd.DataFrame(data)

# Load DataFrame
df = pd.read_parquet('quic_text.parquet')

In [9]:
df

,Label,Data,num_of_packets
0,Youtube,"[[1522982445.960145000, 0, 1412, 1], [15229824...",7288
1,Youtube,"[[1522939930.491890000, 0, 1412, 1], [15229399...",22529
2,Youtube,"[[1522994330.247572000, 0, 1412, 1], [15229943...",17938
3,Youtube,"[[1522908947.040100000, 0, 1412, 1], [15229089...",22709
4,Youtube,"[[1523000044.440979000, 0, 86, 1], [1523000044...",26621
...,...,...,...
3927,Google Drive,"[[1522841219.402012000, 0, 161, 1], [152284121...",11682
3928,Google Drive,"[[1522835303.978634000, 0, 566, 1], [152283530...",10763
3929,Google Drive,"[[1522782530.426202000, 0, 86, 1], [1522782530...",10133
3930,Google Drive,"[[1522763269.225023000, 0, 75, 1], [1522763269...",15547
3931,Google Drive,"[[1522845824.936935000, 0, 174, 1], [152284582...",17175

In [16]:
# Process the DataFrame to convert 'Data' to NumPy arrays
processed_df = process_packet_data(df)
processed_df

,Label,Data,num_of_packets
0,Youtube,"[[0, 1412, 1], [0.000268936, 950, 1], [0.00041...",7288
1,Youtube,"[[0, 1412, 1], [0.000302076, 352, 1], [0.00041...",22529
2,Youtube,"[[0, 1412, 1], [0.0256422, 1412, 0], [0.027286...",17938
3,Youtube,"[[0, 1412, 1], [0.000291824, 909, 1], [0.00042...",22709
4,Youtube,"[[0, 86, 1], [0.017108, 86, 0], [0.0172191, 74...",26621
...,...,...,...
3927,Google Drive,"[[0, 161, 1], [0.00175095, 143, 1], [0.018368,...",11682
3928,Google Drive,"[[0, 566, 1], [2.98023e-05, 112, 1], [0.000402...",10763
3929,Google Drive,"[[0, 86, 1], [0.014925, 86, 0], [0.0150189, 74...",10133
3930,Google Drive,"[[0, 75, 1], [0.0138259, 86, 0], [3.16017, 119...",15547
3931,Google Drive,"[[0, 174, 1], [0.00058198, 143, 1], [0.021709,...",17175

In [17]:
processed_df.drop(columns=['num_of_packets'], inplace= True)
processed_df

             Label                                               Data
0          Youtube  [[0, 1412, 1], [0.000268936, 950, 1], [0.00041...
1          Youtube  [[0, 1412, 1], [0.000302076, 352, 1], [0.00041...
2          Youtube  [[0, 1412, 1], [0.0256422, 1412, 0], [0.027286...
3          Youtube  [[0, 1412, 1], [0.000291824, 909, 1], [0.00042...
4          Youtube  [[0, 86, 1], [0.017108, 86, 0], [0.0172191, 74...
...            ...                                                ...
3927  Google Drive  [[0, 161, 1], [0.00175095, 143, 1], [0.018368,...
3928  Google Drive  [[0, 566, 1], [2.98023e-05, 112, 1], [0.000402...
3929  Google Drive  [[0, 86, 1], [0.014925, 86, 0], [0.0150189, 74...
3930  Google Drive  [[0, 75, 1], [0.0138259, 86, 0], [3.16017, 119...
3931  Google Drive  [[0, 174, 1], [0.00058198, 143, 1], [0.021709,...

[3932 rows x 2 columns]

In [18]:
# Save Features to CSV file
processed_df.to_csv("lopez_features.csv", index=False)

# Save DataFrame to a Parquet file using pyarrow
processed_df.to_parquet('lopez_features.parquet', engine='pyarrow')

# (parquet doesn't work with 2d array)

In [4]:
# Sample DataFrame with random packet data
def generate_random_packet_data(num_packets=10):
    import random
    packets = []
    for _ in range(num_packets):
        timestamp = f"{random.uniform(1522933033, 1522933050):.9f}"  # Random timestamp
        delta_time = f"{random.uniform(0.0001, 1.5):.6f}"            # Random delta time
        size = str(random.randint(50, 1500))                         # Random packet size between 50 and 1500 bytes
        direction = str(random.randint(0, 1))                        # Random direction (0 or 1)
        packets.append([timestamp, delta_time, size, direction])
    return packets

'''
# Generate sample data
data = {
    'Label': ['Youtube', 'Google Doc', 'Google Drive', 'Youtube', 'Google Doc', 'Google Drive'],
    'Data': [
        generate_random_packet_data(40),  # Generating more than 32 packets to test truncation
        generate_random_packet_data(40),
        generate_random_packet_data(40),
        generate_random_packet_data(40),
        generate_random_packet_data(40),
        generate_random_packet_data(40)
    ]
}
'''

"\n# Generate sample data\ndata = {\n    'Label': ['Youtube', 'Google Doc', 'Google Drive', 'Youtube', 'Google Doc', 'Google Drive'],\n    'Data': [\n        generate_random_packet_data(40),  # Generating more than 32 packets to test truncation\n        generate_random_packet_data(40),\n        generate_random_packet_data(40),\n        generate_random_packet_data(40),\n        generate_random_packet_data(40),\n        generate_random_packet_data(40)\n    ]\n}\n"